name: Code Guidelines
# https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#coding-rules

on: [push, pull_request]

jobs:
  build:

    name: Lint code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Lint shell scripts with Shellcheck
        run: docker run --rm -v "$PWD:/mnt" koalaman/shellcheck-alpine:stable find /mnt -type f -name '*.sh' -exec shellcheck '{}' +

      - name: EditorConfig check
        run: npx editorconfig-checker

      - name: Lint <nproxy> Dockerfile (hadolint)
        run:  docker run -i --rm hadolint/hadolint < nproxy/Dockerfile

      - name: Lint <mkcert> Dockerfile (hadolint)
        run:  docker run -i --rm hadolint/hadolint < mkcert/Dockerfile

      # t3kit10
      - name: Lint <t3kit10-php7.4-fpm-nginx-buster> Dockerfile (hadolint)
        run:  docker run -i --rm hadolint/hadolint < t3kit10/php7.4-fpm-nginx-buster/Dockerfile

      # t3kit11
      - name: Lint <t3kit11-php8-fpm-nginx-buster> Dockerfile (hadolint)
        run:  docker run -i --rm hadolint/hadolint < t3kit11/php8-fpm-nginx-buster/Dockerfile

      # t3kit12 - docker build -t t3kit/12-php8-fpm-nginx-bookworm:1.0.0 .
      - name: Lint <t3kit12-php8-fpm-nginx-bookworm> Dockerfile (hadolint)
        run:  docker run -i --rm hadolint/hadolint < t3kit12/php8-fpm-nginx-bookworm/Dockerfile
