name: Code Guidelines
# https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#coding-rules

on: [push, pull_request]

jobs:
  build:

    name: Lint code

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Lint shell scripts with Shellcheck
        run: docker run --rm -v "$PWD:/mnt" koalaman/shellcheck-alpine:stable find . -type f -name '*.sh' -exec shellcheck '{}' +

      - run: npm install eclint

      - name: EditorConfig check
        run: node_modules/eclint/bin/eclint.js check "**/*.{sh,yml,yaml,json,xml,xlf,html,ini,conf}"

      - name: EditorConfig check Dockerfiles
        run: node_modules/eclint/bin/eclint.js check "**/Dockerfile"

      - name: Lint <nproxy> Dockerfile
        run:  docker run -i hadolint/hadolint < nproxy/Dockerfile

      - name: Lint <mkcert> Dockerfile
        run:  docker run -i hadolint/hadolint < mkcert/Dockerfile

      # t3kit8.9
      - name: Lint <t3kit89-php7.3-apache2.4-ubuntu18.04> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit8.9/php7.3-apache2.4-ubuntu18.04/Dockerfile

      - name: Lint <t3kit89-php7.4-apache2.4-ubuntu18.04> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit8.9/php7.4-apache2.4-ubuntu18.04/Dockerfile

      - name: Lint <t3kit89-php7.4-apache2.4-buster> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit8.9/php7.4-apache2.4-buster/Dockerfile

      # t3kit10
      - name: Lint <t3kit10-php7.2-apache2.4-ubuntu18.04> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit10/php7.2-apache2.4-ubuntu18.04/Dockerfile

      - name: Lint <t3kit10-php7.3-apache2.4-ubuntu18.04> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit10/php7.3-apache2.4-ubuntu18.04/Dockerfile

      - name: Lint <t3kit10-php7.3-apache2.4-stretch> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit10/php7.3-apache2.4-stretch/Dockerfile

      - name: Lint <t3kit10-php7.4-apache2.4-buster> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit10/php7.4-apache2.4-buster/Dockerfile

      - name: Lint <t3kit10-php7.4-fpm-buster> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit10/php7.4-fpm-buster/Dockerfile

      - name: Lint <t3kit10-nginx1.19-buster> Dockerfile
        run:  docker run -i hadolint/hadolint < t3kit10/nginx1.19-buster/Dockerfile


