name: Docker images
# https://github.com/t3kit/t3kit-starter#local-development-environment-based-on-docker

on: [push, pull_request]

jobs:

  nproxy:
    name: nproxy
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <nproxy>
        run: DOCKER_BUILDKIT=1 docker -D build -t nproxy nproxy/

      - name: Run nginx-proxy for t3kit
        run: docker run -d -p=80:80 --name=nproxy -v=/var/run/docker.sock:/tmp/docker.sock:ro nproxy

      - name: Run whoami container with env VIRTUAL_HOST=t3kit10.local
        run: docker run -d -e VIRTUAL_HOST=t3kit10.local jwilder/whoami

      - name: Show running containers
        run: docker ps

      - name: Sleep 10s
        uses: maddox/actions/sleep@master
        with:
          args: "10"

      - name: curl t3kit10.local
        run: "curl -fsSLI -H 'Host: t3kit10.local' --url 'localhost/'"

  mkcert:
    name: mkcert
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <mkcert>
        run: DOCKER_BUILDKIT=1 docker -D build -t mkcert mkcert/

      - name: Run mkcert t3kit_first_setup
        run: docker run --rm t3kit/mkcert:1.0.0 t3kit_first_setup

  # t3kit8.9
  t3kit89-php73-apache24-ubuntu1804:
    name: t3kit89-php7.3-apache2.4-ubuntu18.04
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit89-php7.3-apache2.4-ubuntu18.04>
        run: DOCKER_BUILDKIT=1 docker -D build -t t3kit89-php7.3-apache2.4-ubuntu18.04 t3kit8.9/php7.3-apache2.4-ubuntu18.04/

      - name: Run <t3kit89-php7.3-apache2.4-ubuntu18.04>
        run: docker run -d --name=t3kit89-php7.3-apache2.4-ubuntu18.04 t3kit89-php7.3-apache2.4-ubuntu18.04


      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit89-php7.3-apache2.4-ubuntu18.04 curl -fsSLI localhost

  t3kit89-php74-apache24-ubuntu1804:
    name: t3kit89-php7.4-apache2.4-ubuntu18.04
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit89-php7.4-apache2.4-ubuntu18.04>
        run: DOCKER_BUILDKIT=1 docker -D build -t t3kit89-php7.4-apache2.4-ubuntu18.04 t3kit8.9/php7.4-apache2.4-ubuntu18.04/

      - name: Run <t3kit89-php7.4-apache2.4-ubuntu18.04>
        run: docker run -d --name=t3kit89-php7.4-apache2.4-ubuntu18.04 t3kit89-php7.4-apache2.4-ubuntu18.04


      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit89-php7.4-apache2.4-ubuntu18.04 curl -fsSLI localhost

  t3kit89-php74-apache24-buster:
    name: t3kit89-php7.4-apache2.4-buster
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit89-php7.4-apache2.4-buster>
        run: DOCKER_BUILDKIT=1 docker -D build -t t3kit/8.9-php7.4-apache2.4-buster t3kit8.9/php7.4-apache2.4-buster/

      - name: Run <t3kit89-php7.4-apache2.4-buster>
        run: docker run -d --name=t3kit89-php7.4-apache2.4-buster t3kit/8.9-php7.4-apache2.4-buster


      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit89-php7.4-apache2.4-buster curl -fsSLI localhost

  # t3kit10
  t3kit10-php74-apache24-buster:
    name: t3kit10-php7.4-apache2.4-buster
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit10-php7.4-apache2.4-buster>
        run: DOCKER_BUILDKIT=1 docker -D build -t t3kit10-php7.4-apache2.4-buster t3kit10/php7.4-apache2.4-buster/

      - name: Run <t3kit10-php7.4-apache2.4-buster>
        run: docker run -d --name=t3kit10-php7.4-apache2.4-buster t3kit10-php7.4-apache2.4-buster

      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit10-php7.4-apache2.4-buster curl -fsSLI localhost

  t3kit10-php74-fpm-nginx-buster:
    name: t3kit10-php7.4-fpm-nginx-buster
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit10-php7.4-fpm-nginx-buster>
        run: DOCKER_BUILDKIT=1 docker -D build -t t3kit10-php7.4-fpm-nginx-buster t3kit10/php7.4-fpm-nginx-buster/

      - name: Run <t3kit10-php7.4-fpm-nginx-buster>
        run: docker run -d --name=t3kit10-php7.4-fpm-nginx-buster t3kit10-php7.4-fpm-nginx-buster

      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit10-php7.4-fpm-nginx-buster curl -fsSLI localhost
