name: Build Docker images
# https://github.com/t3kit/t3kit-starter#quick-start-a-new-project-on-t3kit-base

on: [push, pull_request]

jobs:

  nproxy:
    name: nproxy
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <nproxy>
        run: docker -D build -t nproxy nproxy/

      - name: Run nginx-proxy for t3kit
        run: docker run -d -p=80:80 --name=nproxy -v=/var/run/docker.sock:/tmp/docker.sock:ro nproxy

      - name: Run whoami container with env VIRTUAL_HOST=t3kit10.local
        run: docker run -d -e VIRTUAL_HOST=t3kit10.local jwilder/whoami

      - name: Show nproxy config
        run:  docker exec nproxy cat /etc/nginx/conf.d/default.conf

      - name: Show nproxy logs
        run: docker logs nproxy

      - name: Show running containers
        run: docker ps

      - name: Sleep 10s
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: curl t3kit10.local
        run: "curl -vfsSLI -H 'Host: t3kit10.local' --url 'localhost/'"

  mkcert:
    name: mkcert
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <mkcert>
        run: docker -D build -t mkcert mkcert/

      - name: Run mkcert t3kit_first_setup
        run: docker run --rm t3kit/mkcert:1.0.0 t3kit_first_setup

  # t3kit10
  t3kit10-php74-apache24-buster:
    name: t3kit10-php7.4-apache2.4-buster
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit10-php7.4-apache2.4-buster>
        run: docker -D build -t t3kit10-php7.4-apache2.4-buster t3kit10/php7.4-apache2.4-buster/

      - name: Run <t3kit10-php7.4-apache2.4-buster>
        run: docker run -d --name=t3kit10-php7.4-apache2.4-buster t3kit10-php7.4-apache2.4-buster

      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit10-php7.4-apache2.4-buster curl -vfsSLI localhost

  t3kit10-php74-fpm-nginx-buster:
    name: t3kit10-php7.4-fpm-nginx-buster
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit10-php7.4-fpm-nginx-buster>
        run: docker -D build -t t3kit10-php7.4-fpm-nginx-buster t3kit10/php7.4-fpm-nginx-buster/

      - name: Run <t3kit10-php7.4-fpm-nginx-buster>
        run: docker run -d --name=t3kit10-php7.4-fpm-nginx-buster t3kit10-php7.4-fpm-nginx-buster

      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit10-php7.4-fpm-nginx-buster curl -vfsSLI localhost

  t3kit11-php8-fpm-nginx-buster:
    name: t3kit11-php8-fpm-nginx-buster
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Docker build <t3kit11-php8-fpm-nginx-buster>
        run: docker -D build -t t3kit11-php8-fpm-nginx-buster t3kit11/php8-fpm-nginx-buster/

      - name: Run <t3kit11-php8-fpm-nginx-buster>
        run: docker run -d --name=t3kit11-php8-fpm-nginx-buster t3kit11-php8-fpm-nginx-buster

      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i t3kit11-php8-fpm-nginx-buster curl -vfsSLI localhost
