name: Docker images
# https://github.com/t3kit/t3kit-starter#local-development-environment-based-on-docker

on: [push, pull_request]

jobs:

  nproxy:
    name: nproxy
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <nproxy>
        run: docker -D build -t nproxy nproxy/

      - name: Run nginx-proxy for t3kit
        run: docker run -d -p=80:80 --name=nproxy -v=/var/run/docker.sock:/tmp/docker.sock:ro nproxy

      - name: Run whoami container with env VIRTUAL_HOST=t3kit9.local
        run: docker run -d -e VIRTUAL_HOST=t3kit9.local jwilder/whoami

      - name: Show running containers
        run: docker ps

      - name: Sleep 10s
        uses: maddox/actions/sleep@master
        with:
          args: "10"

      - name: curl t3kit9.local
        run: "curl -vfsSL -H 'Host: t3kit9.local' --url 'localhost/'"


  ubuntu1804-php72-apache24:
    name: ubuntu18.04-php7.2-apache2.4
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <ubuntu18.04-php7.2-apache2.4>
        run: docker -D build -t ubuntu18.04-php7.2-apache2.4 ubuntu18.04/php7.2-apache2.4/

      - name: Run <ubuntu18.04-php7.2-apache2.4>
        run: docker run -d --name=ubuntu18.04-php7.2-apache2.4 ubuntu18.04-php7.2-apache2.4

      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i ubuntu18.04-php7.2-apache2.4 curl -vfsSL localhost


  ubuntu1804-php73-apache24:
    name: ubuntu18.04-php7.3-apache2.4
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <ubuntu18.04-php7.3-apache2.4>
        run: docker -D build -t ubuntu18.04-php7.3-apache2.4 ubuntu18.04/php7.3-apache2.4/

      - name: Run <ubuntu18.04-php7.3-apache2.4>
        run: docker run -d --name=ubuntu18.04-php7.3-apache2.4 ubuntu18.04-php7.3-apache2.4


      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i ubuntu18.04-php7.3-apache2.4 curl -vfsSL localhost

  php73-apache24-stretch:
    name: php7.3-apache2.4-stretch
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <php7.3-apache2.4-stretch>
        run: docker -D build -t php7.3-apache2.4-stretch php7.3-apache2.4-stretch/

      - name: Run <php7.3-apache2.4-stretch>
        run: docker run -d --name=php7.3-apache2.4-stretch php7.3-apache2.4-stretch


      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i php7.3-apache2.4-stretch curl -vfsSL localhost
