name: Docker images
# https://github.com/t3kit/t3kit-starter#local-development-environment-based-on-docker

on: [push, pull_request]

jobs:

  nproxy:
    name: nproxy
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <nproxy>
        run: docker -D build -t nproxy nproxy/

      - name: Run nginx-proxy for t3kit
        run: docker run -d -p=80:80 --name=nproxy -v=/var/run/docker.sock:/tmp/docker.sock:ro nproxy

      - name: Run whoami container with env VIRTUAL_HOST=t3kit10.local
        run: docker run -d -e VIRTUAL_HOST=t3kit10.local jwilder/whoami

      - name: Show running containers
        run: docker ps

      - name: Sleep 10s
        uses: maddox/actions/sleep@master
        with:
          args: "10"

      - name: curl t3kit10.local
        run: "curl -vfsSL -H 'Host: t3kit10.local' --url 'localhost/'"


  t3kit10-php72-apache24-ubuntu1804:
    name: php7.2-apache2.4-ubuntu18.04
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <php7.2-apache2.4-ubuntu18.04>
        run: DOCKER_BUILDKIT=1 docker -D build -t php7.2-apache2.4-ubuntu18.04 t3kit10/php7.2-apache2.4-ubuntu18.04/

      - name: Run <php7.2-apache2.4-ubuntu18.04>
        run: docker run -d --name=php7.2-apache2.4-ubuntu18.04 php7.2-apache2.4-ubuntu18.04

      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i php7.2-apache2.4-ubuntu18.04 curl -vfsSL localhost


  t3kit10-php73-apache24-ubuntu1804:
    name: php7.3-apache2.4-ubuntu18.04
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <php7.3-apache2.4-ubuntu18.04>
        run: DOCKER_BUILDKIT=1 docker -D build -t php7.3-apache2.4-ubuntu18.04 t3kit10/php7.3-apache2.4-ubuntu18.04/

      - name: Run <php7.3-apache2.4-ubuntu18.04>
        run: docker run -d --name=php7.3-apache2.4-ubuntu18.04 php7.3-apache2.4-ubuntu18.04


      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i php7.3-apache2.4-ubuntu18.04 curl -vfsSL localhost

  t3kit10-php73-apache24-stretch:
    name: php7.3-apache2.4-stretch
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Docker build <php7.3-apache2.4-stretch>
        run: DOCKER_BUILDKIT=1 docker -D build -t php7.3-apache2.4-stretch t3kit10/php7.3-apache2.4-stretch/

      - name: Run <php7.3-apache2.4-stretch>
        run: docker run -d --name=php7.3-apache2.4-stretch php7.3-apache2.4-stretch


      - name: Show running containers
        run: docker ps

      - name: curl localhost
        run: docker exec -i php7.3-apache2.4-stretch curl -vfsSL localhost
